### ISSUE TITLE
The Pretrained Model for "aitod_DNTR_mask.py"

### ISSUE THREAD

**Issue by dango89emo** [hoiliu-0801/DNTR#10]
I appreciate this awesome work and I am currently going to try finetune DNTR to my own dataset.

But along the way I have a trouble with the training configuration.  
https://github.com/hoiliu-0801/DNTR/blob/b66d48f79484bb89297f7c84678f58aabc1c5e4f/mmdet-dntr/configs/aitod-dntr/aitod_DNTR_mask.py#L227

Apparently, it loads from a pretrained model but I could not find any information of it in the paper.
So my question is if I could set that line of pretraining to `load_from = None`.

If it is not true, which configuration is used for pretraining?

I am looking forward to your reply.

**Comment by hoiliu-0801** [comment]
I will update our pre-trained weights soon. 
Yes, you can set load_from=None to get your own pre-trained weights.

**Comment by rookie0607** [comment]
> 我将很快更新我们的预训练权重。 是的，您可以设置 load_from=None 来获取您自己的预训练权重。

更新了吗 @hoiliu-0801

**Comment by hoiliu-0801** [comment]
Yes, I update the readme and we will release the improved weights ASAP. Please find the weights on the google drive.

**Comment by hoiliu-0801** [comment]
I have uploaded the new pre-trained weight recently. Thanks for your patience.
