### ISSUE TITLE
如何实现DNTR在VisDrone2019 val中AP50达到论文中所提到的53.8？

### ISSUE THREAD

**Issue by lancer121387** [hoiliu-0801/DNTR#16]
我使用的配置是configs/aitod-dntr/visdrone_RS_baseline.py   模型收敛后在VisDrone2019 val上的AP50只有40
期待您的回答

**Comment by hoiliu-0801** [comment]
RS_baseline並不是DNTR，指的是DetectoRS，是否有將DN-FPN加上去呢? 計算分數要使用visdrone 提供的matlab tool，分數會更準確 https://github.com/VisDrone/VisDrone2018-DET-toolkit。

**Comment by lancer121387** [comment]
> RS_baseline並不是DNTR，指的是DetectoRS，是否有將DN-FPN加上去呢? 計算分數要使用visdrone 提供的matlab tool，分數會更準確 https://github.com/VisDrone/VisDrone2018-DET-toolkit

感谢您的回复

**Comment by LvRuH** [comment]
> RS_baseline並不是DNTR，指的是DetectoRS，是否有將DN-FPN加上去呢? 計算分數要使用visdrone 提供的matlab tool，分數會更準確 https://github.com/VisDrone/VisDrone2018-DET-toolkit

您好，请问您的意思是训练时仍然遵循mmdet-dntr/configs/_base_/datasets/visdrone_detection.py和mmdet-dntr/mmdet/datasets/visdrone.py相关配置，训练完成后利用visdrone 提供的matlab tool进行评估吗？我已经将DN-FPN和Trans rcnn加上去，但是最终的结果仍和您论文的结果相差将近5个点。期待您的回复

**Comment by xoxososw** [comment]
> RS_baseline並不是DNTR，指的是DetectoRS，是否有將DN-FPN加上去呢? 計算分數要使用visdrone 提供的matlab tool，分數會更準確 https://github.com/VisDrone/VisDrone2018-DET-toolkit

您好，请问如何将DN-FPN加上去呢？我看到您有提到DN-FPN在two-stages这个文件中，请问如何加入到visdrone的代码中呢？

**Comment by Huangzimin123** [comment]
> > RS_baseline并不是DNTR，指的是DetectoRS，是否有将DN-FPN加上去呢？计算分数要使用visdrone 提供的matlab tool，分数会更准确 https://github.com/VisDrone/VisDrone2018-DET-toolkit
> 
> 您好，请问您的意思是训练时仍然遵循mmdet-dntr/configs/_base_/datasets/visdrone_detection.py和mmdet-dntr/mmdet/datasets/visdrone.py 相关配置，训练完成后利用visdrone提供的matlab tool进行评估吗？我已经将DN-FPN和Trans rcnn加上去，但是最终的结果仍和您论文的结果相差将近5个点。期待您的回复

你好，我想请问你是如何将DN-FPN和Trans rcnn加上去的。
