### ISSUE TITLE
关于日志

### ISSUE THREAD

**Issue by znoifhdegh** [hoiliu-0801/DNTR#18]
敬爱的作者您好,首先感谢您的贡献,我对您的工作非常感兴趣,希望您能分享一下您DETR在aitod数据集上的36epochs的日志,我将不甚感激,期待您的回复

**Comment by hoiliu-0801** [comment]
DETR的是用https://github.com/hoiliu-0801/DQ-DETR跑的  log沒有特別存檔
有需要的話我可以提供DNTR的log

**Comment by znoifhdegh** [comment]
> DETR的是用[https://github.com/hoiliu-0801/DQ-DETR跑的](https://github.com/hoiliu-0801/DQ-DETR%E8%B7%91%E7%9A%84) log沒有特別存檔 有需要的話我可以提供DNTR的log

您好,我也很需要DNTR的log, 再次感谢您的工作以及回复对我的帮助,万分谢谢

**Comment by znoifhdegh** [comment]
> DETR的是用[https://github.com/hoiliu-0801/DQ-DETR跑的](https://github.com/hoiliu-0801/DQ-DETR%E8%B7%91%E7%9A%84) log沒有特別存檔 有需要的話我可以提供DNTR的log

很抱歉再次打扰您,如果您方便的话,希望您分享一下DNTR的log,再次感谢,期待您的回复

**Comment by hoiliu-0801** [comment]
以下為DNTR log文件給您參考, 謝謝！
[20241106_145707.log](https://github.com/user-attachments/files/17947894/20241106_145707.log)
[20241106_145707.log.json](https://github.com/user-attachments/files/17947895/20241106_145707.log.json)

**Comment by znoifhdegh** [comment]
> 以下為DNTR log文件給您參考, 謝謝！ [20241106_145707.log](https://github.com/user-attachments/files/17947894/20241106_145707.log) [20241106_145707.log.json](https://github.com/user-attachments/files/17947895/20241106_145707.log.json)

非常感谢您的回复,在这里再次向您致谢,但由于设备的限制,复现不了您的代码,如果您方便的话,希望您能分享一下36个epoch的日志,学习率缩减策略在(24, 33)的时候,不好意思再次麻烦您.当然,如果您没有36epoch的日志,您可以忽略此条请求

**Comment by hoiliu-0801** [comment]
I trained for a total of 48 epochs, but the best result was achieved at epoch 36. The files provided above include the logs up to epoch 48. For the hardware, we only use a consumer-grade GPU, 3090 GPU, with batch size 2.
