### ISSUE TITLE
关于训练

### ISSUE THREAD

**Issue by znoifhdegh** [hoiliu-0801/DNTR#19]
您好,感谢您的贡献,请问一下您为什么复现时损失为nan,参数均与您文章中一致.望解答,感激不尽!

**Comment by hoiliu-0801** [comment]
This issue occurs due to the old mmdet version.
You can either resume from the pre-trained weights or adjust the coefficient lambda from 0.1 to 0.001.

**Comment by znoifhdegh** [comment]
> This issue occurs due to the old mmdet version. You can either resume from the pre-trained weights or adjust the coefficient lambda from 0.1 to 0.001.

Sorry to bother you again. Will adjusting the lambda parameter affect the reproducibility and accuracy of the experiment? Could you provide the pre-trained weights? Thank you

**Comment by hoiliu-0801** [comment]
Please refer to the README for pre-trained weights.

**Comment by znoifhdegh** [comment]
> Please refer to the README for pre-trained weights.



> Please refer to the README for pre-trained weights.

**Comment by znoifhdegh** [comment]
> Please refer to the README for pre-trained weights.

Thank you for your reply. Wishing you good health, smooth work, and fruitful achievements.
