### ISSUE TITLE
configs/dntr/aitod_dntr_r50_1x.py

### ISSUE THREAD

**Issue by LvRuH** [hoiliu-0801/DNTR#2]
Hello,thank you for sharing the code,but I can't find configs/dntr/aitod_dntr_r50_1x.py

**Comment by hoiliu-0801** [comment]
Sorry for the confusion. I've updated the name to aitod_DNTR_mask.py.  You may try it again.

**Comment by LvRuH** [comment]
> Sorry for the confusion. I've updated the name to aitod_DNTR_mask.py. You may try it again.

Thank u！
