### ISSUE TITLE
Regarding the issue of bounding boxes with a size of 0 in the AI-TOD v2 dataset

### ISSUE THREAD

**Issue by gyuilLim** [hoiliu-0801/DNTR#4]
I am currently working with the AI-TOD v2 dataset and have encountered an issue with some of the bounding box annotations in the JSON files. Specifically, I have noticed instances where the bounding box dimensions are given as [1, 4, 0, 16], resulting in a width (w) of 0.

I would greatly appreciate it if you could provide some insight into how this issue was addressed in your work. In particular, I am interested in understanding the following:

How were bounding boxes with a width of 0 handled? Were these bounding boxes removed, corrected, or otherwise processed in a specific way?
How was the issue of images with no remaining objects managed? If the removal of such bounding boxes resulted in images with no detectable objects, what steps were taken to address this?

**Comment by hoiliu-0801** [comment]
We have noticed the presence of noisy labels in the AI-TOD V1&V2 dataset (https://arxiv.org/abs/2401.08056). 
To ensure a fair comparison with other methods, we did not address the noisy labels algorithmically in this work. If you correct the labels, the evaluation score will be no longer fair.
My opinion is to remove the 0 width boxes in the trainval set and test with the original test set.
For aerial images, it's common to have images without detectable objects, so you can omit this issue and proceed with training as usual.
