### ISSUE TITLE
The baseline experiment of Faster R-CNN.

### ISSUE THREAD

**Issue by xuexiaozhou** [hoiliu-0801/DNTR#5]
Hello, I conducted a baseline experiment on the VisDrone2019 dataset using a Faster R-CNN model with a ResNet-50 backbone and FPN, following the settings in the paper. The input size for both the training and test sets was (1333, 800), and the final average precision was 28.2%. Where did I go wrong? Why is the precision so much higher than the results reported in the paper?

**Comment by hoiliu-0801** [comment]
The result of Faster R-CNN is referenced in this work: https://arxiv.org/abs/2112.10415. 
The resolution is correct! I think the improved results may due to the updated mmdet version.

**Comment by xuexiaozhou** [comment]
> Faster R-CNN 的结果引用于此文：https://arxiv.org/abs/2112.10415。 分辨率正确！我认为结果的改善可能是由于更新了 mmdet 版本。

Will the results improve so much after the mmdet update? Did you not reproduce the baseline during your experiments? If the baseline results are already much better than before, how can you prove that the improvements are due to your own module?

**Comment by hoiliu-0801** [comment]
DetectoRS is the reproduced baseline, which is the degenerated model of DNTR (DetectoRS+DN-FPN+Trans-RCNN). Please refer to the implementation details and the experiments to see the improvements.
