### ISSUE TITLE
The code of Transformer-based models.

### ISSUE THREAD

**Issue by dyl96** [hoiliu-0801/DNTR#6]
Hello author, may I ask if it is convenient for you to share the code of Transformer-based models in the paper? For academic purposes and will also cite your paper. Thank you very much！

**Comment by hoiliu-0801** [comment]
You may refer to "mmdet-dntr/configs_ori" to see the DETR series.
The latest mmdet version also supports DINO and Conditional DETR.
Our code for the transformer results will be released soon at https://github.com/Katie0723/DQ-DETR. Thank you for the citation.

**Comment by dyl96** [comment]
Thank you！May I ask if the Params, FLOPs, and accuracy of different categories of Transformer based methods in the DQ-DETR paper can be reported?

**Comment by hoiliu-0801** [comment]
You can run mmdet-dntr/tools/analysis_tools/get_flops.py to calculate them.
