### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by wh1090220084** [hoiliu-0801/DNTR#7]
Hello, author, I couldn't find DN-FPN and Trans R-CNN. Could you please tell me where they are?

**Comment by hoiliu-0801** [comment]
For Trans R-CNN, refer to the file located at mmdet-dntr/mmdet/models/roi_heads/cascade_roi_head_cas_t2t_new_jit_mask.py. For DN-FPN, you can find it in mmdet-dntr/mmdet/models/detectors/two_stage.py (issue #3).
